### ISSUE TITLE
Appolo 2.0 issues

### ISSUE THREAD

**Issue by alonisser** [shmoop207/appolo-express#9]
1. Having appolo moved to using ES6 is a great move. but isn't backwards compatible.. 

I think this should have been done in a new "appolo2" project in not in the master branch, since now there is no way to fix or add functionality to non ES6 branch.

2. The readme examples are still using appolo-class. not compatible with new ES6 class are they?

**Comment by shmoop207** [comment]
there is not backwards compatible because with es6 there is no need for appolo class so it's completely removed and I also wanted to write appolo with the new es6 features to make it more stable and fast.

there is a brunch 1.x for support to old appolo if you need anything changed I can publish update to 1.x brunch.

the docs will be updated soon as there are still small changes to the new appolo syntax.

you can also use node 4.x with the appolo 1.x but I strongly recommend to move to the new syntax.

**Comment by alonisser** [comment]
Thanks @shmoop207  I missed the branch 1.x still existing.. We are not ready yet for node 4.1 (some dependencies not compiling.. ) Thanks for that.
